# 백엔드 도커파일
FROM python:3.9-slim

WORKDIR /app


# RUN apt-get update && apt-get install -y libpq-dev gcc

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install flask

COPY . .

ENV FLASK_APP=api/index.py

EXPOSE 8000

CMD ["flask", "run", "--host=0.0.0.0", "--port=8000"]
